environment_name          = "dev"
resource_group_name       = "rg-market-risk-intelligence-dev"
storage_account_name      = "mriskinteldev001"
storage_container_name    = "market-risk"
key_vault_name            = "kv-market-risk-dev"
data_factory_name         = "adf-market-risk-dev"
databricks_workspace_name = "adb-market-risk-dev"
tenant_id                 = "00000000-0000-0000-0000-000000000000"
enable_eventhub           = true
eventhub_namespace_name   = "evh-market-risk-dev"
eventhub_name             = "market-signal-events"
catalog_name              = "finance_dev"
adls_prefix               = "lakehouse/dev"
databricks_secret_scope   = "market-risk-scope-dev"
fred_api_key_secret_key   = "fred-api-key"
notification_email        = "risk-alerts-dev@example.com"

